# MPLP Protocol v1.0.0 — Frozen Specification
# Freeze Date: 2025-12-03
# Status: FROZEN (no breaking changes permitted)
# Governance: MPLP Protocol Governance Committee (MPGC)
# © 2026 Bangshi Beijing Network Technology Limited Company
# License: Apache-2.0
# Any normative change requires a new protocol version.

packages:
  # Build sources (dev workspace)
  - "packages/sources/sdk-ts"
  # Publish sources (NPM)
  - "packages/npm/*"
  # Examples
  - "examples/*"
