/**
 * MPLP Protocol v1.0.0 — Frozen Specification
 * Freeze Date: 2025-12-03
 * Status: FROZEN (no breaking changes permitted)
 * Governance: MPLP Protocol Governance Committee (MPGC)
 *
 * © 2025 邦士（北京）网络科技有限公司. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * http://www.apache.org/licenses/LICENSE-2.0
 */

// @ts-nocheck
import { compile } from 'json-schema-to-typescript';
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, existsSync } from 'fs';
import { join, basename, relative } from 'path';

const SCHEMAS_DIR = join(__dirname, '../schemas/v2');
const OUTPUT_DIR = join(__dirname, '../packages/core-protocol/src/types');

// Ensure output directories exist
if (!existsSync(OUTPUT_DIR)) mkdirSync(OUTPUT_DIR, { recursive: true });
const COMMON_OUTPUT_DIR = join(OUTPUT_DIR, 'common');
if (!existsSync(COMMON_OUTPUT_DIR)) mkdirSync(COMMON_OUTPUT_DIR, { recursive: true });

async function generate() {
    const files = getAllFiles(SCHEMAS_DIR);
    console.log(`Found ${files.length} schemas to process.`);

    for (const file of files) {
        if (!file.endsWith('.schema.json')) continue;

        try {
            const schema = JSON.parse(readFileSync(file, 'utf8'));
            const filename = basename(file);
            let outputPath = '';
            let bannerComment = '/* eslint-disable */\n/**\n * This file was automatically generated by json-schema-to-typescript.\n * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,\n * and run json-schema-to-typescript to regenerate this file.\n */';

            if (file.includes('common')) {
                const name = filename.replace('.schema.json', '');
                outputPath = join(COMMON_OUTPUT_DIR, `${name}.ts`);
            } else {
                const name = filename.replace('mplp-', '').replace('.schema.json', '');
                outputPath = join(OUTPUT_DIR, `${name}.ts`);
            }

            // Compile
            const ts = await compile(schema, schema.title || filename, {
                cwd: SCHEMAS_DIR,
                bannerComment,
                style: { singleQuote: true },
                // Avoid generating duplicate types for common refs if possible,
                // but for now let's just generate.
                // To handle refs correctly between files is complex.
                // A simpler approach for P5 is to allow duplication or use a custom resolver.
                // But let's see if default works.
                ignoreMinAndMaxItems: true,
            });

            writeFileSync(outputPath, ts);
            console.log(`Generated ${outputPath}`);

        } catch (e) {
            console.error(`Error generating ${file}:`, e);
        }
    }

    createIndexFile(OUTPUT_DIR);
    createIndexFile(COMMON_OUTPUT_DIR);
}

function getAllFiles(dirPath: string, arrayOfFiles: string[] = []) {
    const files = readdirSync(dirPath);
    files.forEach(function (file) {
        if (statSync(dirPath + "/" + file).isDirectory()) {
            arrayOfFiles = getAllFiles(dirPath + "/" + file, arrayOfFiles);
        } else {
            if (file.endsWith(".schema.json")) {
                arrayOfFiles.push(join(dirPath, file));
            }
        }
    });
    return arrayOfFiles;
}

function createIndexFile(dir: string) {
    const files = readdirSync(dir);
    let content = '';
    files.forEach(file => {
        if (file.endsWith('.ts') && file !== 'index.ts') {
            const name = file.replace('.ts', '');
            content += `export * from './${name}';\n`;
        }
    });
    writeFileSync(join(dir, 'index.ts'), content);
}

generate();
