/**
 * MPLP Protocol v1.0.0 — Frozen Specification
 * Freeze Date: 2025-12-03
 * Status: FROZEN (no breaking changes permitted)
 * Governance: MPLP Protocol Governance Committee (MPGC)
 *
 * © 2025 邦士（北京）网络科技有限公司. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * http://www.apache.org/licenses/LICENSE-2.0
 */

// @ts-nocheck
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, existsSync } from 'fs';
import { join, basename, dirname } from 'path';

const SCHEMAS_DIR = join(__dirname, '../schemas/v2');
const OUTPUT_DIR = join(__dirname, '../packages/core-protocol/src/types');
const COMMON_OUTPUT_DIR = join(OUTPUT_DIR, 'common');

// Ensure output directories exist
if (!existsSync(OUTPUT_DIR)) mkdirSync(OUTPUT_DIR, { recursive: true });
if (!existsSync(COMMON_OUTPUT_DIR)) mkdirSync(COMMON_OUTPUT_DIR, { recursive: true });

// Mapping from schema filename to Interface Name
const schemaToInterface: Record<string, string> = {};

function getAllFiles(dirPath: string, arrayOfFiles: string[] = []) {
    const files = readdirSync(dirPath);
    files.forEach(function (file) {
        if (statSync(dirPath + "/" + file).isDirectory()) {
            arrayOfFiles = getAllFiles(dirPath + "/" + file, arrayOfFiles);
        } else {
            if (file.endsWith(".schema.json")) {
                arrayOfFiles.push(join(dirPath, file));
            }
        }
    });
    return arrayOfFiles;
}

function toPascalCase(str: string): string {
    return str.replace(/(^\w|-\w)/g, (text) => text.replace(/-/, "").toUpperCase());
}

// Pre-scan to build mapping
const files = getAllFiles(SCHEMAS_DIR);
files.forEach(file => {
    const filename = basename(file);
    let interfaceName = '';
    if (file.includes('common')) {
        const name = filename.replace('.schema.json', '');
        interfaceName = `Mplp${toPascalCase(name)}`;
    } else {
        const name = filename.replace('mplp-', '').replace('.schema.json', '');
        interfaceName = toPascalCase(name);
    }
    schemaToInterface[filename] = interfaceName;
});

console.log('Schema Mapping:', schemaToInterface);

function resolveType(schema: any, propName: string): string {
    if (schema.$ref) {
        const ref = schema.$ref;
        if (ref.startsWith('#/definitions/')) {
            return ref.split('/').pop()!;
        }
        // External ref
        const refFile = ref.split('#')[0];
        return 'any';
    }

    if (schema.type === 'string') {
        if (schema.enum) {
            return schema.enum.map((e: string) => `'${e}'`).join(' | ');
        }
        if (schema.format === 'date-time') return 'string';
        return 'string';
    }
    if (schema.type === 'number' || schema.type === 'integer') return 'number';
    if (schema.type === 'boolean') return 'boolean';
    if (schema.type === 'array') {
        const itemType = resolveType(schema.items || {}, '');
        return `${itemType}[]`;
    }
    if (schema.type === 'object') {
        if (schema.additionalProperties === true || !schema.properties) {
            return '{ [key: string]: any }';
        }
        // Inline object definition - simplified
        return 'object';
    }

    return 'any';
}

function generateInterface(name: string, schema: any): string {
    let output = `/**\n * ${schema.description || name}\n */\n`;
    output += `export interface ${name} {\n`;

    if (schema.properties) {
        for (const [key, value] of Object.entries<any>(schema.properties)) {
            const isRequired = schema.required && schema.required.includes(key);
            const type = resolveType(value, key);
            const doc = value.description ? `  /** ${value.description} */\n` : '';
            output += `${doc}  ${key}${isRequired ? '' : '?'}: ${type};\n`;
        }
    }

    // Handle definitions if any (mostly in common schemas)
    if (schema.definitions) {
        // We might need to export these as separate types
    }

    output += '}\n';
    return output;
}

// Main generation loop
for (const file of files) {
    const filename = basename(file);
    const interfaceName = schemaToInterface[filename];
    const content = readFileSync(file, 'utf8');
    const schema = JSON.parse(content);

    let tsContent = `/* eslint-disable */\n// Generated by simple-codegen.ts\n\n`;

    // Add imports
    const imports = new Set<string>();
    // Scan for refs to add imports
    const scanRefs = (obj: any) => {
        if (!obj) return;
        if (obj.$ref && !obj.$ref.startsWith('#')) {
            const refFile = obj.$ref.split('#')[0];
            if (schemaToInterface[refFile]) {
                imports.add(schemaToInterface[refFile]);
            }
        }
        if (typeof obj === 'object') {
            for (const k in obj) scanRefs(obj[k]);
        }
    };
    scanRefs(schema);

    imports.forEach(imp => {
        if (imp !== interfaceName) {
            // Determine relative path
            let importPath = '';
            const isCommon = file.includes('common');
            const isImpCommon = imp.startsWith('Mplp');

            if (isCommon && isImpCommon) importPath = `./${imp.replace('Mplp', '').replace(/(?<!^)([A-Z])/g, "-$1").toLowerCase()}`; // simplified
            else if (!isCommon && isImpCommon) importPath = `./common/${imp.replace('Mplp', '').replace(/(?<!^)([A-Z])/g, "-$1").toLowerCase()}`;
            else if (isCommon && !isImpCommon) importPath = `../${imp.toLowerCase()}`;
            else importPath = `./${imp.toLowerCase()}`;

            // Fix import path logic later, for now assume flat or common/
            // Actually, let's just use the filename mapping
        }
    });

    // Simplified import logic:
    // If in common, import from . (other common)
    // If in root, import from ./common/ (common) or . (other root)

    // We need a reverse map from Interface to FilePath relative to output

    tsContent += generateInterface(interfaceName, schema);

    // Handle definitions (append them)
    if (schema.definitions) {
        for (const [defName, defSchema] of Object.entries<any>(schema.definitions)) {
            tsContent += `\nexport type ${defName} = ${resolveType(defSchema, defName)};\n`;
        }
    }

    const outputPath = file.includes('common')
        ? join(COMMON_OUTPUT_DIR, filename.replace('.schema.json', '.ts'))
        : join(OUTPUT_DIR, filename.replace('mplp-', '').replace('.schema.json', '.ts'));

    writeFileSync(outputPath, tsContent);
    console.log(`Generated ${outputPath}`);
}

// Create indices
function createIndex(dir: string) {
    const files = readdirSync(dir);
    let content = '';
    files.forEach(f => {
        if (f.endsWith('.ts') && f !== 'index.ts') {
            content += `export * from './${f.replace('.ts', '')}';\n`;
        }
    });
    writeFileSync(join(dir, 'index.ts'), content);
}

createIndex(OUTPUT_DIR);
createIndex(COMMON_OUTPUT_DIR);
