import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for 4-tier IA structure (B-1 refactor)
 * 
 * Tiers:
 * 1. SPECIFICATION - Protocol mirror (derived)
 * 2. EVALUATION - Governance & verification (derived)
 * 3. GUIDES - Examples & usage (illustrative)
 * 4. META - Site-level information
 * 
 * Phase 1 Migration: All categories now use doc links to index.mdx files
 * instead of generated-index to ensure proper SEO and content rendering.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Introduction',
      link: { type: 'doc', id: 'introduction/index' },
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'introduction' }],
    },

    // --------------------------------------------------------
    // SPECIFICATION (Tier 1)
    // --------------------------------------------------------
    {
      type: 'category',
      label: 'Specification',
      collapsible: false,
      className: 'sidebar-section-title',
      items: [
        {
          type: 'category',
          label: 'Architecture',
          link: { type: 'doc', id: 'specification/architecture/index' },
          collapsed: false,
          items: [{ type: 'autogenerated', dirName: 'specification/architecture' }],
        },
        {
          type: 'category',
          label: 'Modules',
          link: { type: 'doc', id: 'specification/modules/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'specification/modules' }],
        },
        {
          type: 'category',
          label: 'Profiles',
          link: { type: 'doc', id: 'specification/profiles/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'specification/profiles' }],
        },
        {
          type: 'category',
          label: 'Observability',
          link: { type: 'doc', id: 'specification/observability/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'specification/observability' }],
        },
        {
          type: 'category',
          label: 'Integration',
          link: { type: 'doc', id: 'specification/integration/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'specification/integration' }],
        },
      ]
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },

    // --------------------------------------------------------
    // EVALUATION (Tier 2)
    // --------------------------------------------------------
    {
      type: 'category',
      label: 'Evaluation',
      collapsible: false,
      className: 'sidebar-section-title',
      items: [
        {
          type: 'category',
          label: 'Golden Flows',
          link: { type: 'doc', id: 'evaluation/golden-flows/index' },
          collapsed: false,
          items: [{ type: 'autogenerated', dirName: 'evaluation/golden-flows' }],
        },
        {
          type: 'category',
          label: 'Validation Lab',
          link: { type: 'doc', id: 'evaluation/validation-lab/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'evaluation/validation-lab' }],
        },
        {
          type: 'category',
          label: 'Governance',
          link: { type: 'doc', id: 'evaluation/governance/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'evaluation/governance' }],
        },
        {
          type: 'category',
          label: 'Conformance',
          link: { type: 'doc', id: 'evaluation/conformance/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'evaluation/conformance' }],
        },
        {
          type: 'category',
          label: 'Standards',
          link: { type: 'doc', id: 'evaluation/standards/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'evaluation/standards' }],
        },
        {
          type: 'category',
          label: 'Tests',
          link: { type: 'doc', id: 'evaluation/tests/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'evaluation/tests' }],
        },
      ]
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },

    // --------------------------------------------------------
    // GUIDES (Tier 3)
    // --------------------------------------------------------
    {
      type: 'category',
      label: 'Guides',
      collapsible: false,
      className: 'sidebar-section-title',
      items: [
        {
          type: 'category',
          label: 'Examples',
          link: { type: 'doc', id: 'guides/examples/index' },
          collapsed: false,
          items: [{ type: 'autogenerated', dirName: 'guides/examples' }],
        },
        {
          type: 'category',
          label: 'SDK',
          link: { type: 'doc', id: 'guides/sdk/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'guides/sdk' }],
        },
        {
          type: 'category',
          label: 'Runtime',
          link: { type: 'doc', id: 'guides/runtime/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'guides/runtime' }],
        },
        {
          type: 'category',
          label: 'Enterprise',
          link: { type: 'doc', id: 'guides/enterprise/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'guides/enterprise' }],
        },
        {
          type: 'category',
          label: 'Adoption',
          link: { type: 'doc', id: 'guides/adoption/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'guides/adoption' }],
        },
      ]
    },
    {
      type: 'html',
      value: '<div class="sidebar-divider"></div>',
    },

    // --------------------------------------------------------
    // META (Tier 4)
    // --------------------------------------------------------
    {
      type: 'category',
      label: 'Meta',
      collapsible: false,
      className: 'sidebar-section-title',
      items: [

        {
          type: 'category',
          label: 'Release',
          link: { type: 'doc', id: 'meta/release/index' },
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'meta/release' }],
        },
      ]
    },
  ],
};

export default sidebars;

